### ISSUE TITLE
Specified key was too long

### ISSUE THREAD

**Issue by weylermaldonado** [kawadhiya21/mysql-migrations#10]
This is my migrations.js file

```javascript
const mysql = require('mysql');
const migration = require('mysql-migrations');

const connection = mysql.createPool({
    connectionLimit : 10,
    host: 'host',
    user: 'user',
    password: 'mypass',
    database: 'my_db'
});

migration.init(connection, __dirname + '/migrations');
```

but when I run `node migration.js add migration create_table_users` get this error:
```bash
ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
```
but I don't create any table, and all credentials and database are correct. Any ideas?

**Comment by kawadhiya21** [comment]
I think it could be one of these:

1. https://github.com/sequelize/sequelize/issues/4171
2. https://github.com/mozilla/chronicle/issues/98

**Comment by kawadhiya21** [comment]
Closing the issue.
