### ISSUE TITLE
Multiple statement migrations?

### ISSUE THREAD

**Issue by fuschini** [kawadhiya21/mysql-migrations#16]
Is there a way to do this?

If no, is it planned on the roadmap?

**Comment by kawadhiya21** [comment]
What is that? Can you give an example?

**Comment by kawadhiya21** [comment]
Closing since no response

**Comment by llibdude** [comment]
What they meant was could you do something like

```javascript
module.exports = {
  up: "SELECT 1; SELECT 1;"
  down: '',
};
```

Which from my test, no, you can't.

**Comment by kawadhiya21** [comment]
Are you still looking for that feature?

**Comment by fuschini** [comment]
Yes @llibdude, that's what I meant.

@kawadhiya21, I'm not looking for it anymore because I started using another lib for my migrations that supports that (typeorm native migrations).
